//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONTRATOS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CONTRATOS()
        {
            this.DETALLE_COSTOS = new HashSet<DETALLE_COSTOS>();
            this.DOCUMENTOS = new HashSet<DOCUMENTOS>();
            this.ORDEN_PAGO = new HashSet<ORDEN_PAGO>();
            this.DETALLE_TRAMITES = new HashSet<DETALLE_TRAMITES>();
        }
    
        public long ID_CONTRATO { get; set; }
        public System.DateTime FECHA_INICIO { get; set; }
        public Nullable<System.DateTime> FECHA_TERMINO { get; set; }
        public long ID_PRESUPUESTO { get; set; }
        public Nullable<double> COSTO_ESTIMADO { get; set; }
        public string DOCUMENTO_GENERADO { get; set; }
        public string CORREO_ENVIADO { get; set; }
        public string COMENTARIOS { get; set; }
        public long ID_ASISTENTE { get; set; }
    
        public virtual ASISTENTES ASISTENTES { get; set; }
        public virtual PRESUPUESTO PRESUPUESTO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DETALLE_COSTOS> DETALLE_COSTOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DOCUMENTOS> DOCUMENTOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ORDEN_PAGO> ORDEN_PAGO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DETALLE_TRAMITES> DETALLE_TRAMITES { get; set; }
    }
}
