//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETALLE_TRAMITES
    {
        public long ID_TRAMITES { get; set; }
        public Nullable<long> ID_CONTRATO { get; set; }
        public string CODIGO_TRAMITE { get; set; }
        public string NOMBRE_TRAMITE { get; set; }
        public Nullable<long> COSTO { get; set; }
        public string STATUS { get; set; }
        public Nullable<System.DateTime> TIMESTAMP { get; set; }
        public Nullable<System.DateTime> CREATED { get; set; }
        public Nullable<long> ID_PRESUPUESTO { get; set; }
    
        public virtual CONTRATOS CONTRATOS { get; set; }
        public virtual PRESUPUESTO PRESUPUESTO { get; set; }
    }
}
