//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LexAbogadosWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETALLE_COSTOS
    {
        public long ID_DETALLE_COSTO { get; set; }
        public long ID_CONTRATO { get; set; }
        public string TIPO_GASTO { get; set; }
        public Nullable<double> MONTO { get; set; }
        public byte[] BOLETA_DIGITALIZADA { get; set; }
        public string FECHA { get; set; }
        public string AUTORIZADA_REEMBOLZO { get; set; }
        public Nullable<long> ASISTENTE_RESPONZABLE { get; set; }
        public string NOMBRE_NOTARIA { get; set; }
        public string DIRECCION_NOTARIA { get; set; }
    
        public virtual CONTRATOS CONTRATOS { get; set; }
    }
}
