//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DOCUMENTOS
    {
        public long ID_DOCUMENTO { get; set; }
        public Nullable<long> ID_CONTRATO { get; set; }
        public Nullable<long> ID_PRESUPUESTO { get; set; }
        public System.DateTime FECHA_INGRESO { get; set; }
        public byte[] DOCUMENTO_DIGITAL { get; set; }
        public string PATH { get; set; }
        public string MIME_TYPE { get; set; }
        public string NOMBRE_ARCHIVO { get; set; }
    
        public virtual CONTRATOS CONTRATOS { get; set; }
        public virtual PRESUPUESTO PRESUPUESTO { get; set; }
    }
}
