//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LexAbogadosWeb.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ODAO : DbContext
    {
        public ODAO()
            : base("name=ODAO")
        {
            this.Configuration.LazyLoadingEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ASISTENTES> ASISTENTES { get; set; }
        public DbSet<CAUSALES> CAUSALES { get; set; }
        public DbSet<CLIENTES> CLIENTES { get; set; }
        public DbSet<COMUNAS> COMUNAS { get; set; }
        public DbSet<DETALLE_COSTOS> DETALLE_COSTOS { get; set; }
        public DbSet<DETALLE_TRAMITES> DETALLE_TRAMITES { get; set; }
        public DbSet<MENU> MENU { get; set; }
        public DbSet<MENU_SUB> MENU_SUB { get; set; }
        public DbSet<ORDEN_PAGO> ORDEN_PAGO { get; set; }
        public DbSet<PLAN_PAGO> PLAN_PAGO { get; set; }
        public DbSet<REGIONES> REGIONES { get; set; }
        public DbSet<TIPO_CLIENTE> TIPO_CLIENTE { get; set; }
        public DbSet<TIPO_ROL> TIPO_ROL { get; set; }
        public DbSet<TRIBUNAL_JUSTICIA> TRIBUNAL_JUSTICIA { get; set; }
        public DbSet<USUARIOS> USUARIOS { get; set; }
        public DbSet<CONTRATOS> CONTRATOS { get; set; }
        public DbSet<DOCUMENTOS> DOCUMENTOS { get; set; }
        public DbSet<PRESUPUESTO> PRESUPUESTO { get; set; }
    }
}
