//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectWebApp.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ODAO : DbContext
    {
        public ODAO()
            : base("name=ODAO")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ASISTENTES> ASISTENTES { get; set; }
        public virtual DbSet<CAUSALES> CAUSALES { get; set; }
        public virtual DbSet<CLIENTES> CLIENTES { get; set; }
        public virtual DbSet<COMUNAS> COMUNAS { get; set; }
        public virtual DbSet<CONTRATOS> CONTRATOS { get; set; }
        public virtual DbSet<DETALLE_COSTOS> DETALLE_COSTOS { get; set; }
        public virtual DbSet<DOCUMENTOS> DOCUMENTOS { get; set; }
        public virtual DbSet<ESTADO> ESTADO { get; set; }
        public virtual DbSet<MENU> MENU { get; set; }
        public virtual DbSet<MENU_SUB> MENU_SUB { get; set; }
        public virtual DbSet<ORDEN_PAGO> ORDEN_PAGO { get; set; }
        public virtual DbSet<PLAN_PAGO> PLAN_PAGO { get; set; }
        public virtual DbSet<PRESUPUESTO> PRESUPUESTO { get; set; }
        public virtual DbSet<REGIONES> REGIONES { get; set; }
        public virtual DbSet<TIPO_CLIENTE> TIPO_CLIENTE { get; set; }
        public virtual DbSet<TIPO_ROL> TIPO_ROL { get; set; }
        public virtual DbSet<USUARIOS> USUARIOS { get; set; }
        public virtual DbSet<DETALLE_TRAMITES> DETALLE_TRAMITES { get; set; }
    }
}
