//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MENU_SUB
    {
        public long MENU_ID { get; set; }
        public string TEXTO { get; set; }
        public string REFERENCIA { get; set; }
        public long ID_ROL { get; set; }
        public long MENU_ID_P { get; set; }
        public string CRUD { get; set; }
        public string CONTROLLER { get; set; }
        public string ACTION { get; set; }
    
        public virtual MENU MENU { get; set; }
        public virtual TIPO_ROL TIPO_ROL { get; set; }
    }
}
