//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDEN_PAGO
    {
        public long ID_ORDEN_PAGO { get; set; }
        public string TIPO_PAGO { get; set; }
        public long ID_CONTRATO { get; set; }
        public Nullable<long> MONTO_TOTAL { get; set; }
        public Nullable<long> ESTADO { get; set; }
        public string IP { get; set; }
        public Nullable<System.DateTime> CREATED { get; set; }
        public Nullable<long> NUMERO_TRANSACCION { get; set; }
        public Nullable<long> CUOTAS { get; set; }
        public Nullable<long> VALOR_CUOTA { get; set; }
    
        public virtual CONTRATOS CONTRATOS { get; set; }
    }
}
