//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRESUPUESTO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PRESUPUESTO()
        {
            this.CONTRATOS = new HashSet<CONTRATOS>();
            this.DOCUMENTOS = new HashSet<DOCUMENTOS>();
            this.DETALLE_TRAMITES = new HashSet<DETALLE_TRAMITES>();
        }
    
        public long ID_PRESUPUESTO { get; set; }
        public string COD_SOLICITUD { get; set; }
        public System.DateTime FECHA { get; set; }
        public string ESTADO_AVANCE { get; set; }
        public string CONTRATADO { get; set; }
        public string OBSERVACIONES { get; set; }
        public Nullable<long> ID_ASISTENTE { get; set; }
        public long ID_CAUSAL { get; set; }
        public Nullable<long> ID_CLIENTE { get; set; }
        public string NOTA { get; set; }
        public Nullable<System.DateTime> FECHA_NOTIFICA { get; set; }
    
        public virtual ASISTENTES ASISTENTES { get; set; }
        public virtual CAUSALES CAUSALES { get; set; }
        public virtual CLIENTES CLIENTES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CONTRATOS> CONTRATOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DOCUMENTOS> DOCUMENTOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DETALLE_TRAMITES> DETALLE_TRAMITES { get; set; }
    }
}
