//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIPO_CLIENTE
    {
        public TIPO_CLIENTE()
        {
            this.CLIENTES = new HashSet<CLIENTES>();
        }
    
        public long ID_TIPO_CLIENTE { get; set; }
        public string NOMBRE_TIPO { get; set; }
        public Nullable<System.DateTime> TIMESTAMP { get; set; }
    
        public virtual ICollection<CLIENTES> CLIENTES { get; set; }
    }
}
