//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIOS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public USUARIOS()
        {
            this.ASISTENTES = new HashSet<ASISTENTES>();
            this.CLIENTES = new HashSet<CLIENTES>();
        }
    
        public string USER { get; set; }
        public string PASS { get; set; }
        public Nullable<System.DateTime> TIMESTAMP { get; set; }
        public long ID_ROL { get; set; }
        public long ID_USUARIO { get; set; }
        public string CORREO { get; set; }
        public string CORREO_SEC { get; set; }
        public string IP { get; set; }
        public string IMG_PROFILE { get; set; }
        public byte[] BINARY_IMAGE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ASISTENTES> ASISTENTES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CLIENTES> CLIENTES { get; set; }
        public virtual TIPO_ROL TIPO_ROL { get; set; }
    }
}
